### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by MisterL2** [singh96aman/Effects-of-alcohol-on-liver#1]
Hello,
I took over the python-util package on PyPi, which now offers alot of cool features. However, this means that the old python-util no longer exists.
I'm posting this because your repository's requirements.txt file specifies a dependency on the old python-util.
This is the current version of the package: https://pypi.org/project/python-util/
Since you don't seem to use it in your project, you are probably fine if you just remove it from your requirements.txt tbh.

**Comment by singh96aman** [comment]
Hi Misterl2,

Yes, it's true, this project is almost 3 years old now. However, If it runs on NGINX server I would have to provide a requirements.txt file which needs to have all these dependencies.
What we should do is an update to the requirements.txt file!

Also, If we are interested please check out a similar project where I am I looking for open source contributors to incorporate NLP in my SVM model on Stock Prediction Model.
https://github.com/singh96aman/MarketWatchBETA

Thanks
